stages:
  - build
  - deploy

main-build-job:
  stage: build
  only:
    - main
  image: node:14
  script:
    - echo "Installing NPM modules..."
    - npm install
    - echo "Compiling the code..."
    - npm run build:prd
    - echo "Compile complete."
    - echo "Copying the public folder..."
    - mv public/* dist
  artifacts:
    paths:
      - dist/

main-deploy-to-s3:
  stage: deploy
  only:
    - main
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp dist/ s3://$S3_BUCKET --recursive

storybook-build-job:
  stage: build
  only:
    - storybook
  image: node:14
  script:
    - echo "Installing NPM modules..."
    - npm install
    - echo "Compiling the code..."
    - npm run build-storybook
    - echo "Compile complete."
  artifacts:
    paths:
      - storybook-static/

storybook-deploy-to-s3:
  stage: deploy
  only:
    - storybook
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp storybook-static/ s3://$S3_BUCKET/storybook-static --recursive
