stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:14
  script:
    - echo "Installing NPM modules..."
    - npm install
    - echo "Compiling the code..."
    - npm run build:prd
    - echo "Compile complete."
    - echo "Copying the public folder..."
    - mv public dist/
  artifacts:
    paths:
      - dist/

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp dist/ s3://$S3_BUCKET --recursive
