stages:
  - build
  - deploy

build-job:
  stage: build
  image: node:10
  script:
    - echo "Installing NPM modules..."
    - npm install
    - echo "Compiling the code..."
    - npm run build
    - echo "Compile complete."
  artifacts:
    paths:
      - build/

deploy to s3:
  stage: deploy
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws --version
    - aws s3 rm s3://$S3_BUCKET --recursive
    - aws s3 cp build/ s3://$S3_BUCKET --recursive
